# Generated by Django 4.2.6 on 2023-10-26 10:50
from typing import Any

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_uid", models.UUIDField(default=None, null=True)),
                ("username", models.CharField(max_length=128)),
                ("url", models.TextField()),
                (
                    "ips",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.GenericIPAddressField(),
                        default=list,
                        size=None,
                    ),
                ),
                ("query_params", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=dict)),
                ("ok", models.BooleanField(default=True)),
                ("error", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("response_size", models.PositiveIntegerField(default=0)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Signup"),
                            (2, "Login"),
                            (3, "Logout"),
                            (4, "Change password"),
                            (5, "Reset password"),
                            (6, "Refresh token"),
                        ]
                    ),
                ),
                ("duration", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(default="")),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant_uid", models.UUIDField(default=None, null=True)),
                (
                    "to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=128), size=None
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("server_response", models.TextField()),
            ],
            options={
                "db_table": "email_logs",
                "ordering": ["-id"],
            },
        ),
    ]
