# Generated by Django 4.2.6 on 2023-10-26 10:50
from typing import Any

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "String"),
                            (2, "Integer"),
                            (3, "Float"),
                            (4, "Date"),
                            (5, "Date time"),
                        ],
                        default=1,
                    ),
                ),
            ],
            options={
                "db_table": "variables",
                "ordering": ["-id"],
            },
        ),
    ]
