# Generated by Django 5.0.2 on 2024-02-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variable",
            old_name="key",
            new_name="uid",
        ),
    ]
