[tool.poetry]
name = "basecode"
version = "1.0.0"
description = "Python basecode project"
authors = ["Son Tran <son@zen8labs.com>"]

[tool.poetry.dependencies]
python = "^3.12"
Django = "^5.0.2"
django-filter = "^23.5"
psycopg2-binary = "^2.9.9"
argon2-cffi = "^23.1.0"
uvicorn = "^0.27.1"
django-ninja = "^1.1.0"
pillow = "^10.2.0"
pyjwt = "^2.8.0"
django-hint = "^0.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
